### ISSUE TITLE
App fails to start "Failed to create webview"

### ISSUE THREAD

**Issue by Bnaya** [MobileChromeApps/cordova-plugin-crosswalk-webview#25]
When starting app with that plugin i'm getting "unfortunately XXX has stopped

This is the filtered logcat  
```
I/ActivityManager( 1657): Timeline: Activity_launch_request id:com.photomania.app time:26546224
I/ActivityManager(  947): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.photomania.app/.CordovaApp} from pid 1657
D/ActivityManager(  947): resumeTopActivityLocked: Restarting ActivityRecord{439f4fc8 u0 com.photomania.app/.CordovaApp t76}
I/ActivityManager(  947): Start proc com.photomania.app for activity com.photomania.app/.CordovaApp: pid=16773 uid=10193 gids={50193, 1028, 1015}
D/SlideAside(10898): [MainService.java:201:handleNewActivity()] oooooo User executes an App : com.photomania.app (filtered)
V/ActivityManager(  947): Moving to RESUMED: ActivityRecord{439f4fc8 u0 com.photomania.app/.CordovaApp t76} (starting new instance)
D/dalvikvm(16773): Trying to load lib /data/app-lib/com.photomania.app-2/libxwalkcore.so 0x42fc0a50
D/dalvikvm(16773): Added shared lib /data/app-lib/com.photomania.app-2/libxwalkcore.so 0x42fc0a50
W/System.err(16773): 	at com.photomania.app.CordovaApp.onCreate(CordovaApp.java:31)
E/AndroidRuntime(16773): Process: com.photomania.app, PID: 16773
E/AndroidRuntime(16773): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.photomania.app/com.photomania.app.CordovaApp}: java.lang.RuntimeException: Failed to create webview. 
E/AndroidRuntime(16773): 	at com.photomania.app.CordovaApp.onCreate(CordovaApp.java:31)
W/ActivityManager(  947):   Force finishing activity com.photomania.app/.CordovaApp
V/ActivityManager(  947): Moving to PAUSING: ActivityRecord{439f4fc8 u0 com.photomania.app/.CordovaApp t76 f}
W/ActivityManager(  947): Activity pause timeout for ActivityRecord{439f4fc8 u0 com.photomania.app/.CordovaApp t76 f}
V/ActivityManager(  947): Moving to PAUSED: ActivityRecord{439f4fc8 u0 com.photomania.app/.CordovaApp t76 f} (due to timeout)
V/ActivityManager(  947): Moving to FINISHING: ActivityRecord{439f4fc8 u0 com.photomania.app/.CordovaApp t76 f}
D/ActivityManager(  947): allPausedActivitiesComplete: r=ActivityRecord{439f4fc8 u0 com.photomania.app/.CordovaApp t76 f} state=FINISHING
V/ActivityManager(  947): Moving to DESTROYING: ActivityRecord{439f4fc8 u0 com.photomania.app/.CordovaApp t76 f} (destroy requested)
E/WindowManager(  947): Starting window AppWindowToken{4492f620 token=Token{43a8ebb0 ActivityRecord{439f4fc8 u0 com.photomania.app/.CordovaApp t76}}} timed out
W/ActivityManager(  947): Activity destroy timeout for ActivityRecord{439f4fc8 u0 com.photomania.app/.CordovaApp t76 f}
V/ActivityManager(  947): Moving to DESTROYED: ActivityRecord{439f4fc8 u0 com.photomania.app/.CordovaApp t76 f} (removed from history)
```

And unfiltered logcat:
http://pastebin.com/rN5cF06r

**Comment by Bnaya** [comment]
Its looks like its because the app is missing the android.permission.ACCESS_WIFI_STATE permission.
Why is that mandatory? I've created a clean project with the crosswalk plugin without that permission in android manifest and its working

**Comment by Hirbod** [comment]
It's madatory because crosswalk needs it. They also wrote this down in their official documentation
